### PR TITLE
proposed second decorator for your plugin

### PR DESCRIPTION
**Pull request by ppossanzini**

### CODE REVIEW

**Comment by Scotley** [comment]
Please merge. This second decorator would fix several issues that need workarounds with how property access works with the existing one.

**Comment by Shifu462** [comment]
Personally I think that there is no need for such decorator, and the following code is not a workaround, but the best way to handle `asyncComputed` props.

```ts
@Component<MyComponent>({
    asyncComputed: {
        async myProp() {
            return await someTask();
        }
    }
})
export default class MyComponent extends Vue {
    readonly myProp!: string;

    someFunction() {
        console.log(this.myProp);
    }
}
```

**Comment by ppossanzini** [comment]
Hi Shidu462, you can use your code without any additional decorators to the original plugin, neither vue-async-computed-decorator one. 

In my case i prefer have all code inside the class and not in the component declaration. 


> Personally I think that there is no need for such decorator, and the following code is not a workaround, but the best way to handle `asyncComputed` props.
> 
> ```ts
> @Component<MyComponent>({
>     asyncComputed: {
>         async myProp() {
>             console.log(this); // yes, you can use `this` here
>             return await someTask();
>         }
>     }
> })
> export default class MyComponent extends Vue {
>     readonly myProp!: string;
> 
>     someFunction() {
>         console.log(this.myProp);
>     }
> }
> ```

**Comment by Scotley** [comment]
Any chance of a comment from @foxbenjaminfox about his intentions to merge this second decorator?

**Comment by foxbenjaminfox** [comment]
I think that this second decorator is a bit out of scope for this package. I'd like to keep this package focused on the one thing it does.

That's not to say that this second decorator isn't good! It's a perfectly fine way of using `asyncComputed` with class components, and if you release it as its own package I'd be happy to link to it from the README here.

**Pull request closed without merging**
